---
title: "Draft Quarto document"
author: "Your Name"
format: html
---

## Header 1

```{r setup}
#| include: false
targets::tar_config_set(store = here::here("_targets"))
library(tidyverse)
library(targets)
library(tidymodels)

source(here::here("R/functions.R"))

lipidomics <- tar_read(lipidomics)
```

# Results

```{r}
tar_read(df_stats_by_metabolite) %>%
  mutate(MeanSD = glue::glue("{value_mean} ({value_sd})")) %>% # combine value_mean and value_sd into a new parameter
  select(Metabolite = metabolite, `Mean SD` = MeanSD) %>%
  knitr::kable(caption = "Descriptive Statistics of the Metabolites.") # Make table pretty
```

```{r}
tar_read(fig_metabolite_distribution)
```

## Building the model

```{r}
lipidomics_wide <- lipidomics %>%
  columns_values_to_snake_case(metabolite) %>%
  metabolites_to_wider()

lipidomics_wide
```

```{r}
model_workflow <- create_model_workflow(
  logistic_reg() %>%
    set_engine("glm"),
  lipidomics_wide %>%
    create_recipe_spec(metabolite_cholesterol)
) %>%
  fit(lipidomics_wide) %>%
  tidy_model_output()

model_workflow
```
